spring:
  cloud:
    stream:
      bindings:
        to-uppercase-request:
          destination: to-uppercase-request
        to-uppercase-reply:
          destination: to-uppercase-reply
server:
  port: 8080